# Arithmetic Operation

In [1]:
r = 1000
i = 0.2
total = r * (1+i)
total

1200.0

In [2]:
3 != 2

True

## List

In [3]:
l = [10,20,30,40,50]

In [4]:
l[0]

10

In [5]:
l[-1]

50

In [6]:
len(l)

5

In [7]:
l.append(80)

In [9]:
l

[10, 20, 30, 40, 50, 80]

In [8]:
l1 = [10,20,"test","mest",8.4,100]

In [9]:
l1

[10, 20, 'test', 'mest', 8.4, 100]

In [17]:
l1[0] = 11
l1

[11, 20, 'test', 'mest', 8.4, 100]

## Tuple

In [15]:
t = (10, 11, 12)

In [18]:
t[1]

11

In [19]:
t[1] = 8

TypeError: 'tuple' object does not support item assignment

## Set

In [20]:
my_list = [1,1,2,3,4,4,5,6]
my_list

[1, 1, 2, 3, 4, 4, 5, 6]

In [21]:
my_set = set(my_list)
my_set

{1, 2, 3, 4, 5, 6}

In [22]:
a = {8,4,5,8,9,63,5,4,4}
b = {5,4,6,8,9,22,1,1}
a.intersection(b)

{4, 5, 8, 9}

## Dictionary

In [29]:
customers = {
    'Alise': 25,
    'Bob': 18,
    'Mark': 40
}

In [30]:
customers

{'Alise': 25, 'Bob': 18, 'Mark': 40}

In [3]:
customers = [
    {"name": "Anna", "revenue": 150},
    {"name": "David", "revenue": 220},
    {"name": "Mariam", "revenue": 90}
]

customers

[{'name': 'Anna', 'revenue': 150},
 {'name': 'David', 'revenue': 220},
 {'name': 'Mariam', 'revenue': 90}]

In [1]:
import pandas as pd

In [4]:
df = pd.DataFrame(customers)
df

     name  revenue
0    Anna      150
1   David      220
2  Mariam       90

## Creating a DataFrame

In [11]:
import pandas as pd

data = {
    "name": ["Anna", "David", "Mariam"],
    "revenue": [150, 220, 90],
    "city": ["Yerevan", "Tbilisi", "Warsaw"]
}

df = pd.DataFrame(data)
df

     name  revenue     city
0    Anna      150  Yerevan
1   David      220  Tbilisi
2  Mariam       90   Warsaw

In [7]:
df.info()
df.shape
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     3 non-null      str
 1   revenue  3 non-null      int64
 2   city     3 non-null      str
dtypes: int64(1), str(2)
memory usage: 204.0 bytes

Index(['name', 'revenue', 'city'], dtype='str')

# Basic DataFrame Manipulation

## Selecting Columns

In [ ]:
df["revenue"]
df[["name", "revenue"]]

     name  revenue
0    Anna      150
1   David      220
2  Mariam       90

## Adding a Column

In [18]:
t = 0.2
df["revenue_ater_tax"] = df["revenue"] * (1 - t)
df

     name  revenue     city  revenue_after_tax  revenue_ater_tax
0    Anna      150  Yerevan              120.0             120.0
1   David      220  Tbilisi              176.0             176.0
2  Mariam       90   Warsaw               72.0              72.0

## Removing a Column

In [19]:
df.drop("revenue_after_tax", axis = 1)

     name  revenue     city  revenue_ater_tax
0    Anna      150  Yerevan             120.0
1   David      220  Tbilisi             176.0
2  Mariam       90   Warsaw              72.0

## Filtering Rows

In [22]:
df[df["revenue"] > 100]

    name  revenue     city  revenue_after_tax  revenue_ater_tax
0   Anna      150  Yerevan              120.0             120.0
1  David      220  Tbilisi              176.0             176.0

In [23]:
df

     name  revenue     city  revenue_after_tax  revenue_ater_tax
0    Anna      150  Yerevan              120.0             120.0
1   David      220  Tbilisi              176.0             176.0
2  Mariam       90   Warsaw               72.0              72.0

## Updating Values

In [28]:
df.loc[df["revenue"] < 100, "segment"] = "Low"
df.loc[df["revenue"] > 100, "segment"] = "High"
df

     name  revenue     city  revenue_after_tax  revenue_ater_tax segment
0    Anna      150  Yerevan              120.0             120.0    High
1   David      220  Tbilisi              176.0             176.0    High
2  Mariam       90   Warsaw               72.0              72.0     Low

# Conditional Statements

## The Basic if Statement

In [35]:
revenue = 150
if revenue > 100:
    print("High Revenue"),
print("Analysis Complete")

High Revenue
Analysis Complete

In [33]:
revenue = 180
if revenue > 200:
    print("Very High revenue"),
elif revenue > 100:
    print("High revenue"),
elif revenue > 50:
    print("Medium revenue"),
else:
    print("Low revenue")

High revenue

## Indentation | Why It Matters

In [6]:
revenue = 150

if revenue > 100:
    print("High revenue")

print("Analysis complete")

High revenue
Analysis complete

## Using elif for Multiple Conditions

In [37]:
revenue = 280

if revenue > 200:
    print("Very high revenue")
elif revenue > 100:
    print("High revenue")
elif revenue > 50:
    print("Medium revenue")
else:
    print("Low revenue")

Very high revenue

## Boolean Expressions and Comparison Operators

In [41]:
100 == 50
100 > 50
100 != 50

True

## Combining Conditions with Logical Operators

In [9]:
revenue = 150
is_active = True

if revenue > 100 and is_active:
    print("Target customer")

Target customer

In [42]:
is_active = False

if not is_active:
    print("Customer is inactive")

Customer is inactive

## Nested Conditional Statements

In [11]:
revenue = 150
region = "EU"

if revenue > 100:
    if region == "EU":
        print("High EU revenue")
    else:
        print("High non-EU revenue")

High EU revenue

# Loops

## The Basic for Loop

In [12]:
sales = [100, 200, 150]

for value in sales:
    print(value)

100
200
150

## Loop With Accumulation

In [13]:
sales = [100, 200, 150]

total = 0

for value in sales:
    total = total + value

total

450

In [43]:
sales = [100, 200, 150]
sum = sum(sales)
sum

450

## Loop With Conditional Logic

In [46]:
sales = [100, 200, 150, 50]

for value in sales:
    if value > 100:
        print("High value:", value),
    else:
        print("Low value:", value)

Low value: 100
High value: 200
High value: 150
Low value: 50

## Looping Over Dictionaries

In [24]:
customer = {
    "name": "Anna",
    "revenue": 150,
    "city": "Yerevan"
}

for key in customer:
    print(key, ":", customer[key])

name : Anna
revenue : 150
city : Yerevan

In [26]:
customer.items()

dict_items([('name', 'Anna'), ('revenue', 150), ('city', 'Yerevan')])

In [29]:
customer = {
    "name": "Anna",
    "revenue": 150,
    "city": "Yerevan"
}

for key in customer:
    print(key, ":", customer[key])

name : Anna
revenue : 150
city : Yerevan

In [30]:
for key, value in customer.items():
    print(key, value)

name Anna
revenue 150
city Yerevan

## The range() Function

In [31]:
for i in range(5):
    print(i)

0
1
2
3
4

## Nested Loops

In [32]:
for i in range(3):
    for j in range(2):
        print("i =", i, ", j =", j)

i = 0 , j = 0
i = 0 , j = 1
i = 1 , j = 0
i = 1 , j = 1
i = 2 , j = 0
i = 2 , j = 1

## List Comprehension

In [ ]:
# traditional loop:
sales = [100, 200, 150]

new_sales = []

for value in sales:
    new_sales.append(value * 1.2)

new_sales

[120.0, 240.0, 180.0]

In [ ]:
# Now using list comprehension:
sales = [100, 200, 150]

new_sales = [value * 1.2 for value in sales]
new_sales

[120.0, 240.0, 180.0]

## With Conditional Filtering

In [ ]:
# You can add a condition:
sales = [100, 200, 150, 50]

high_sales = [value for value in sales if value > 120]
high_sales

[200, 150]

In [ ]:
# Traditional version:
high_sales = []

for value in sales:
    if value > 120:
        high_sales.append(value)

high_sales

[200, 150]

# Homework