## Importing packages

In [5]:
import pandas as pd

## Importing the data

In [6]:
df_orders = pd.read_csv('../data/raw/orders.csv')

print(df_orders.columns)
print(df_orders.shape)
df_orders.head()

Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order'],
      dtype='str')
(3421083, 7)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [ ]:
# Reading data
df_orders_products_train = pd.read_csv('../data/raw/order_products_train.csv')
print(df_orders_products_train.columns)
print(df_orders_products_train.shape)
df_orders_products_train.head()

Index(['order_id', 'product_id', 'add_to_cart_order', 'reordered'], dtype='str')
(1384617, 4)

   order_id  product_id  add_to_cart_order  reordered
0         1       49302                  1          1
1         1       11109                  2          1
2         1       10246                  3          0
3         1       49683                  4          0
4         1       43633                  5          1

In [8]:
df_products = pd.read_csv("../data/raw/products.csv")
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [9]:
df_departments = pd.read_csv('../data/raw/departments.csv')
print(df_departments.columns)
print(df_departments.shape)
df_departments.head()

Index(['department_id', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
       '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21'],
      dtype='str')
(1, 22)

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

In [10]:
df_aisles = pd.read_csv('../data/raw/aisles.csv')
print(df_aisles.columns)
print(df_aisles.shape)
df_aisles.head()

Index(['aisle_id', 'aisle'], dtype='str')
(134, 2)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

## Descriptive statistics

In [7]:
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.421083e+06,3.214874e+06
mean,1.710542e+06,1.029782e+05,1.715486e+01,2.776219e+00,1.345202e+01,1.111484e+01
std,9.875817e+05,5.953372e+04,1.773316e+01,2.046829e+00,4.226088e+00,9.206737e+00
min,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,8.552715e+05,5.139400e+04,5.000000e+00,1.000000e+00,1.000000e+01,4.000000e+00
50%,1.710542e+06,1.026890e+05,1.100000e+01,3.000000e+00,1.300000e+01,7.000000e+00
75%,2.565812e+06,1.543850e+05,2.300000e+01,5.000000e+00,1.600000e+01,1.500000e+01
max,3.421083e+06,2.062090e+05,1.000000e+02,6.000000e+00,2.300000e+01,3.000000e+01

In [8]:
pd.options.display.float_format = '{:,.2f}'.format
df_orders.describe()

,order_id,user_id,order_number,order_dow,order_hour_of_day,days_since_prior_order
count,"3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,421,083.00","3,214,874.00"
mean,"1,710,542.00","102,978.21",17.15,2.78,13.45,11.11
std,"987,581.74","59,533.72",17.73,2.05,4.23,9.21
min,1.00,1.00,1.00,0.00,0.00,0.00
25%,"855,271.50","51,394.00",5.00,1.00,10.00,4.00
50%,"1,710,542.00","102,689.00",11.00,3.00,13.00,7.00
75%,"2,565,812.50","154,385.00",23.00,5.00,16.00,15.00
max,"3,421,083.00","206,209.00",100.00,6.00,23.00,30.00

## Missing values

In [9]:
df_orders.isna().sum()

order_id                       0
user_id                        0
eval_set                       0
order_number                   0
order_dow                      0
order_hour_of_day              0
days_since_prior_order    206209
dtype: int64

## Analytical questions that can be answered from `orders`

How many orders are there in total?
How many unique users are represented?
What is the distribution of eval_set?
On which days do customers place orders most frequently?
At what hours do customers place orders most frequently?
Are missing values in days_since_prior_order meaningful?
Is the first order of a user treated differently from later orders?

In [10]:
df_orders["order_id"].nunique()

3421083

In [11]:
df_orders["user_id"].nunique()

206209

In [12]:
df_orders["eval_set"].value_counts(dropna=False)

eval_set
prior    3214874
train     131209
test       75000
Name: count, dtype: int64

In [13]:
df_orders["order_dow"].value_counts().sort_index()

order_dow
0    600905
1    587478
2    467260
3    436972
4    426339
5    453368
6    448761
Name: count, dtype: int64

In [14]:
df_orders["order_hour_of_day"].value_counts().sort_index()

order_hour_of_day
0      22758
1      12398
2       7539
3       5474
4       5527
5       9569
6      30529
7      91868
8     178201
9     257812
10    288418
11    284728
12    272841
13    277999
14    283042
15    283639
16    272553
17    228795
18    182912
19    140569
20    104292
21     78109
22     61468
23     40043
Name: count, dtype: int64

In [15]:
df_ohod = df_orders['order_hour_of_day'].value_counts().reset_index().sort_values('order_hour_of_day')
df_ohod.head()

    order_hour_of_day  count
18                  0  22758
19                  1  12398
21                  2   7539
23                  3   5474
22                  4   5527

In [16]:
df_ohod.to_csv('../data/processed/ohod.csv')

In [17]:
df_ohod.to_excel('../data/processed/ohod.xlsx')

In [11]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [12]:
df_departments = df_departments.transpose()

In [14]:
df_departments.head()

                        0
department_id  department
1                  frozen
2                   other
3                  bakery
4                 produce

In [16]:
df_departments = df_departments.transpose()

In [17]:
df_departments.head()

,department_id,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,department,frozen,other,bakery,produce,alcohol,international,beverages,pets,dry goods pasta,...,meat seafood,pantry,breakfast,canned goods,dairy eggs,household,babies,snacks,deli,missing

In [18]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [19]:
df_dep_t = df_departments.T

In [20]:
df_dep_t.reset_index(inplace=True)

In [21]:
new_header = df_dep_t.iloc[0]

In [22]:
df_dep_t_new = df_dep_t[1:]

In [24]:
df_dep_t_new.columns = new_header   

df_dep_t_new.head()

0 department_id department
1             1     frozen
2             2      other
3             3     bakery
4             4    produce
5             5    alcohol

In [25]:
df_dep_t_new.head()

0 department_id department
1             1     frozen
2             2      other
3             3     bakery
4             4    produce
5             5    alcohol

In [26]:
df_orders.to_csv("../data/processed/orders_cleaned.csv", index=False)

In [27]:
df_products.to_csv("../data/processed/products_cleaned.csv", index=False)

In [28]:
df_dep_t_new.to_csv("../data/processed/departments_t.csv", index=False)

In [29]:
df_departments_t = pd.read_csv("../data/processed/departments_t.csv")

In [30]:
df_departments_t.head()

   department_id department
0              1     frozen
1              2      other
2              3     bakery
3              4    produce
4              5    alcohol

In [31]:
df_products.head()

,product_id,product_name,aisle_id,department_id,prices
0,1,Chocolate Sandwich Cookies,61,19,5.8
1,2,All-Seasons Salt,104,13,9.3
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5
4,5,Green Chile Anytime Sauce,5,13,4.3

In [32]:
df_products_departments = pd.merge(
    df_products,
    df_departments_t,
    on="department_id",
    how="left"
)

df_products_departments.head()

,product_id,product_name,aisle_id,department_id,prices,department
0,1,Chocolate Sandwich Cookies,61,19,5.8,snacks
1,2,All-Seasons Salt,104,13,9.3,pantry
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,beverages
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,frozen
4,5,Green Chile Anytime Sauce,5,13,4.3,pantry

In [33]:
df_aisles.head()

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation

In [34]:
df_products_enriched = pd.merge(
    df_products_departments,
    df_aisles,
    on="aisle_id",
    how="left"
)

df_products_enriched.head()

,product_id,product_name,aisle_id,department_id,prices,department,aisle
0,1,Chocolate Sandwich Cookies,61,19,5.8,snacks,cookies cakes
1,2,All-Seasons Salt,104,13,9.3,pantry,spices seasonings
2,3,Robust Golden Unsweetened Oolong Tea,94,7,4.5,beverages,tea
3,4,Smart Ones Classic Favorites Mini Rigatoni Wit...,38,1,10.5,frozen,frozen meals
4,5,Green Chile Anytime Sauce,5,13,4.3,pantry,marinades meat preparation

In [35]:
df_orders_train = df_orders[df_orders["eval_set"] == "train"]
df_orders_train.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
10,1187899,1,train,11,4,8,14.0
25,1492625,2,train,15,1,11,30.0
49,2196797,5,train,5,0,11,6.0
74,525192,7,train,21,2,11,6.0
78,880375,8,train,4,1,14,10.0

In [36]:
df_orders.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order
0,2539329,1,prior,1,2,8,NaN
1,2398795,1,prior,2,3,7,15.0
2,473747,1,prior,3,3,12,21.0
3,2254736,1,prior,4,4,7,29.0
4,431534,1,prior,5,4,15,28.0

In [37]:
df_train_transaction = pd.merge(
    df_orders_train,
    df_orders_products_train,
    on="order_id",
    how="left"
)

df_train_transaction.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered
0,1187899,1,train,11,4,8,14.0,196,1,1
1,1187899,1,train,11,4,8,14.0,25133,2,1
2,1187899,1,train,11,4,8,14.0,38928,3,1
3,1187899,1,train,11,4,8,14.0,26405,4,1
4,1187899,1,train,11,4,8,14.0,39657,5,1

In [38]:
df_train_analytics = pd.merge(
    df_train_transaction,
    df_products_enriched,
    on="product_id",
    how="left"
)

df_train_analytics.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,aisle_id,department_id,prices,department,aisle
0,1187899,1,train,11,4,8,14.0,196,1,1,Soda,77.0,7.0,9.0,beverages,soft drinks
1,1187899,1,train,11,4,8,14.0,25133,2,1,Organic String Cheese,21.0,16.0,8.6,dairy eggs,packaged cheese
2,1187899,1,train,11,4,8,14.0,38928,3,1,0% Greek Strained Yogurt,120.0,16.0,12.6,dairy eggs,yogurt
3,1187899,1,train,11,4,8,14.0,26405,4,1,XL Pick-A-Size Paper Towel Rolls,54.0,17.0,1.0,household,paper goods
4,1187899,1,train,11,4,8,14.0,39657,5,1,Milk Chocolate Almonds,45.0,19.0,6.8,snacks,candy chocolate

In [39]:
data = ['customers.csv', 'states.csv']

URL = 'https://raw.githubusercontent.com/hovhannisyan91/aca/refs/heads/main/lab/python/data/raw/'

ldf = []
for i in data: 
    df = pd.read_csv(URL+i)
    # քանի որ ցանկանում ենք նաև միացնել տվյալները մենք կարող ենք դա անել միանգամից՝ նախ սկզբում պահելով այն լիստի մեջ
    ldf.append(df)
df_customers = ldf[0]
df_states = ldf[1]
df_customers.head()
df_states.head()
df_customers.rename(columns={'STATE':'state'}, inplace=True)
df_customers_states = df_customers.merge(df_states,on = 'state')
df_customers_states.head()

,user_id,First Name,Surname,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,26711,Deborah,Esquivel,Female,Missouri,48,1/1/2017,3,married,165665,Midwest,West North Central
1,33890,Patricia,Hart,Female,New Mexico,36,1/1/2017,0,single,59285,West,Mountain
2,65803,Kenneth,Farley,Male,Idaho,35,1/1/2017,2,married,99568,West,Mountain
3,125935,Michelle,Hicks,Female,Iowa,40,1/1/2017,0,single,42049,Midwest,West North Central
4,130797,Ann,Gilmore,Female,Maryland,26,1/1/2017,1,married,40374,South,South Atlantic

In [42]:
df_train_analytics_final = df_train_analytics.merge(df_customers_states, on='user_id', how='left')

In [43]:
df_train_analytics_final.head()

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,...,Surname,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,1187899,1,train,11,4,8,14.0,196,1,1,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
1,1187899,1,train,11,4,8,14.0,25133,2,1,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
2,1187899,1,train,11,4,8,14.0,38928,3,1,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
3,1187899,1,train,11,4,8,14.0,26405,4,1,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
4,1187899,1,train,11,4,8,14.0,39657,5,1,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central

In [44]:
df_train_analytics_final.drop(columns=['user_id','eval_set','product_id', 'aisle_id', 'department_id'])

,order_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,product_name,prices,department,...,Surname,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,1187899,11,4,8,14.0,1,1,Soda,9.0,beverages,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
1,1187899,11,4,8,14.0,2,1,Organic String Cheese,8.6,dairy eggs,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
2,1187899,11,4,8,14.0,3,1,0% Greek Strained Yogurt,12.6,dairy eggs,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
3,1187899,11,4,8,14.0,4,1,XL Pick-A-Size Paper Towel Rolls,1.0,household,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
4,1187899,11,4,8,14.0,5,1,Milk Chocolate Almonds,6.8,snacks,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1384701,272231,14,6,14,30.0,4,0,Fabric Softener Sheets,1.4,household,...,Donovan,Female,Iowa,74,9/14/2019,3,married,137969,Midwest,West North Central
1384702,272231,14,6,14,30.0,5,0,Dark Chocolate Mint Snacking Chocolate,2.1,snacks,...,Donovan,Female,Iowa,74,9/14/2019,3,married,137969,Midwest,West North Central
1384703,272231,14,6,14,30.0,6,0,Phish Food Frozen Yogurt,2.7,frozen,...,Donovan,Female,Iowa,74,9/14/2019,3,married,137969,Midwest,West North Central
1384704,272231,14,6,14,30.0,7,0,French Baguette Bread,15.0,bakery,...,Donovan,Female,Iowa,74,9/14/2019,3,married,137969,Midwest,West North Central
1384705,272231,14,6,14,30.0,8,1,Original Multigrain Spoonfuls Cereal,3.3,breakfast,...,Donovan,Female,Iowa,74,9/14/2019,3,married,137969,Midwest,West North Central

In [45]:
df_train_analytics_final.drop(columns=['user_id','eval_set','product_id', 'aisle_id', 'department_id'],inplace=True)

In [46]:
print(df_train_analytics_final.shape)
df_train_analytics_final.head()

(1384706, 22)

,order_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,product_name,prices,department,...,Surname,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,1187899,11,4,8,14.0,1,1,Soda,9.0,beverages,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
1,1187899,11,4,8,14.0,2,1,Organic String Cheese,8.6,dairy eggs,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
2,1187899,11,4,8,14.0,3,1,0% Greek Strained Yogurt,12.6,dairy eggs,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
3,1187899,11,4,8,14.0,4,1,XL Pick-A-Size Paper Towel Rolls,1.0,household,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
4,1187899,11,4,8,14.0,5,1,Milk Chocolate Almonds,6.8,snacks,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central

In [49]:
df_train_analytics_final.to_csv('../data/processed/instacart.csv')

In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [4]:
df_instacart = pd.read_csv('../data/processed/instacart.csv')

In [5]:
df_instacart.head()

,Unnamed: 0,order_id,order_number,order_dow,order_hour_of_day,days_since_prior_order,add_to_cart_order,reordered,product_name,prices,...,Surname,Gender,state,Age,date_joined,n_dependants,fam_status,income,region,division
0,0,1187899,11,4,8,14.0,1,1,Soda,9.0,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
1,1,1187899,11,4,8,14.0,2,1,Organic String Cheese,8.6,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
2,2,1187899,11,4,8,14.0,3,1,0% Greek Strained Yogurt,12.6,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
3,3,1187899,11,4,8,14.0,4,1,XL Pick-A-Size Paper Towel Rolls,1.0,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central
4,4,1187899,11,4,8,14.0,5,1,Milk Chocolate Almonds,6.8,...,Nguyen,Female,Alabama,31,2/17/2019,3,married,40423,South,East South Central

In [8]:
df_instacart.info

<bound method DataFrame.info of          Unnamed: 0  order_id  order_number  order_dow  order_hour_of_day  \
0                 0   1187899            11          4                  8
1                 1   1187899            11          4                  8
2                 2   1187899            11          4                  8
3                 3   1187899            11          4                  8
4                 4   1187899            11          4                  8
...             ...       ...           ...        ...                ...
1384701     1384701    272231            14          6                 14
1384702     1384702    272231            14          6                 14
1384703     1384703    272231            14          6                 14
1384704     1384704    272231            14          6                 14
1384705     1384705    272231            14          6                 14

         days_since_prior_order  add_to_cart_order  reordered  \
0                          14.0                  1          1
1                          14.0                  2          1
2                          14.0                  3          1
3                          14.0                  4          1
4                          14.0                  5          1
...                         ...                ...        ...
1384701                    30.0                  4          0
1384702                    30.0                  5          0
1384703                    30.0                  6          0
1384704                    30.0                  7          0
1384705                    30.0                  8          1

                                   product_name  prices  ...  Surname  Gender  \
0                                          Soda     9.0  ...   Nguyen  Female
1                         Organic String Cheese     8.6  ...   Nguyen  Female
2                      0% Greek Strained Yogurt    12.6  ...   Nguyen  Female
3              XL Pick-A-Size Paper Towel Rolls     1.0  ...   Nguyen  Female
4                        Milk Chocolate Almonds     6.8  ...   Nguyen  Female
...                                         ...     ...  ...      ...     ...
1384701                  Fabric Softener Sheets     1.4  ...  Donovan  Female
1384702  Dark Chocolate Mint Snacking Chocolate     2.1  ...  Donovan  Female
1384703                Phish Food Frozen Yogurt     2.7  ...  Donovan  Female
1384704                   French Baguette Bread    15.0  ...  Donovan  Female
1384705    Original Multigrain Spoonfuls Cereal     3.3  ...  Donovan  Female

           state Age date_joined n_dependants  fam_status  income   region  \
0        Alabama  31   2/17/2019            3     married   40423    South
1        Alabama  31   2/17/2019            3     married   40423    South
2        Alabama  31   2/17/2019            3     married   40423    South
3        Alabama  31   2/17/2019            3     married   40423    South
4        Alabama  31   2/17/2019            3     married   40423    South
...          ...  ..         ...          ...         ...     ...      ...
1384701     Iowa  74   9/14/2019            3     married  137969  Midwest
1384702     Iowa  74   9/14/2019            3     married  137969  Midwest
1384703     Iowa  74   9/14/2019            3     married  137969  Midwest
1384704     Iowa  74   9/14/2019            3     married  137969  Midwest
1384705     Iowa  74   9/14/2019            3     married  137969  Midwest

                   division
0        East South Central
1        East South Central
2        East South Central
3        East South Central
4        East South Central
...                     ...
1384701  West North Central
1384702  West North Central
1384703  West North Central
1384704  West North Central
1384705  West North Central

[1384706 rows x 23 columns]>

In [ ]:
df_instacart = pd.read_parquet("../data/processed/instacart.parquet")
df_instacart.head()

ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - `Import pyarrow` failed. pyarrow is required for parquet support. Use pip or conda to install the pyarrow package.
 - `Import fastparquet` failed. fastparquet is required for parquet support. Use pip or conda to install the fastparquet package.