# Dates

In [1]:
from datetime import datetime, date, timedelta

In [2]:
my_date = date(2026,3,24)

In [3]:
my_date

datetime.date(2026, 3, 24)

In [4]:
type(my_date)

datetime.date

In [5]:
start_date = my_date
end_date = date(2026,4,4)

In [6]:
delta = end_date - start_date
delta

datetime.timedelta(days=11)

In [8]:
type(delta.days)

int

In [9]:
end_date + timedelta(weeks = 1)

datetime.date(2026, 4, 11)

In [10]:
full_datetime = datetime(2024, 7, 1, 14, 30, 0)
full_datetime

datetime.datetime(2024, 7, 1, 14, 30)

In [11]:
today = date.today()
now = datetime.now()

print(f'today is {today}')
print(f'right now is {now}')

today is 2026-03-24
right now is 2026-03-24 20:29:16.264121

## Dates with Pandas

In [3]:
import pandas as pd

df_dates = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "signup_date": ["2024-01-15", "2024-02-20", "2024-03-05", "2024-03-18", "2024-04-10"],
    "last_purchase": ["2024-06-01", "2024-06-15", "2024-07-01", "2024-07-08", "2024-07-12"]
})

df_dates

   customer_id signup_date last_purchase
0          101  2024-01-15    2024-06-01
1          102  2024-02-20    2024-06-15
2          103  2024-03-05    2024-07-01
3          104  2024-03-18    2024-07-08
4          105  2024-04-10    2024-07-12

In [6]:
df_dates.dtypes

customer_id               int64
signup_date      datetime64[us]
last_purchase    datetime64[us]
dtype: object

In [7]:
df_dates["signup_date"] = pd.to_datetime(df_dates["signup_date"])
df_dates["last_purchase"] = pd.to_datetime(df_dates["last_purchase"])

df_dates.dtypes

customer_id               int64
signup_date      datetime64[us]
last_purchase    datetime64[us]
dtype: object

In [8]:
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
dtypes: datetime64[us](2), int64(1)
memory usage: 252.0 bytes

In [9]:
df_dates.to_csv('../data/test.csv', index=False)

In [10]:
test = pd.read_csv('../data/test.csv',parse_dates=['signup_date',
                                                   'last_purchase'],
                                                   dtype={'customer_id':str})
test.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      str
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
dtypes: datetime64[us](2), str(1)
memory usage: 252.0 bytes

In [11]:
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
dtypes: datetime64[us](2), int64(1)
memory usage: 252.0 bytes

In [12]:
df_dates["signup_year"] = df_dates["signup_date"].dt.year
df_dates["signup_month"] = df_dates["signup_date"].dt.month
df_dates["signup_day"] = df_dates["signup_date"].dt.day

In [14]:
df_dates.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    5 non-null      int64
 1   signup_date    5 non-null      datetime64[us]
 2   last_purchase  5 non-null      datetime64[us]
 3   signup_year    5 non-null      int32
 4   signup_month   5 non-null      int32
 5   signup_day     5 non-null      int32
dtypes: datetime64[us](2), int32(3), int64(1)
memory usage: 312.0 bytes

In [15]:
df_dates.head()

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day
0,101,2024-01-15,2024-06-01,2024,1,15
1,102,2024-02-20,2024-06-15,2024,2,20
2,103,2024-03-05,2024-07-01,2024,3,5
3,104,2024-03-18,2024-07-08,2024,3,18
4,105,2024-04-10,2024-07-12,2024,4,10

In [16]:
df_dates["signup_month_name"] = df_dates["signup_date"].dt.month_name()
df_dates["signup_day_name"] = df_dates["signup_date"].dt.day_name()
df_dates["signup_dow"] = df_dates["signup_date"].dt.dayofweek

In [17]:
df_dates["is_weekend"] = (df_dates['signup_date'].dt.day_of_week>=5).astype(int)

In [18]:
df_dates['day_between_signup_purchase'] =  (df_dates['last_purchase'] - df_dates['signup_date']).dt.days

In [19]:
df_dates[df_dates['signup_date']>='2023-06-07']

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_dow,is_weekend,day_between_signup_purchase
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,0,0,138
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,1,0,116
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,0,93

In [20]:
df_dates.sort_values('signup_date', ascending=False)

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_dow,is_weekend,day_between_signup_purchase
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,0,93
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,0,0,112
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,0,118
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,1,0,116
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,0,0,138

In [21]:
df_dates.sort_values('signup_date')

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_dow,is_weekend,day_between_signup_purchase
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,0,0,138
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,1,0,116
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,0,93

In [22]:
list(pd.date_range(start="2024-07-01", periods=7, freq="MS"))

[Timestamp('2024-07-01 00:00:00'),
 Timestamp('2024-08-01 00:00:00'),
 Timestamp('2024-09-01 00:00:00'),
 Timestamp('2024-10-01 00:00:00'),
 Timestamp('2024-11-01 00:00:00'),
 Timestamp('2024-12-01 00:00:00'),
 Timestamp('2025-01-01 00:00:00')]

In [23]:
import pandas as pd

some_date = pd.Timestamp("2024-07-15")

print(f"Original date: {some_date}")
print(f"Beginning of month: {some_date.to_period('M').start_time}")
print(f"End of month: {some_date.to_period('M').end_time}")

Original date: 2024-07-15 00:00:00
Beginning of month: 2024-07-01 00:00:00
End of month: 2024-07-31 23:59:59.999999

In [24]:
df_dates['bom'] = df_dates['signup_date'].dt.to_period('M').dt.start_time.dt.date
df_dates['eom'] = df_dates['signup_date'].dt.to_period('M').dt.end_time.dt.date

In [25]:
df_dates['signup_date'].dt.to_period('M').dt.start_time.dt.date

0    2024-01-01
1    2024-02-01
2    2024-03-01
3    2024-03-01
4    2024-04-01
Name: signup_date, dtype: object